### ISSUE TITLE
posit32_tod yields wrong result

### ISSUE THREAD

**Issue by cjdelisle** [stillwater-sc/universal#100]
Posit32 with bit pattern `0xb0bfe591` should (afaict) correspond to double value `-3.81260083615779876708984375`, this test shows that posit32_tod() is outputting `0.0000000000000000000000000003092334748466...` instead. The test includes `posit32_fromd()` which behaves as expected.

```
static void testp32tod() {
    posit32_t p32;
    p32.v = 0xb0bfe591u;
    double d = -3.8126008361577987670898437500000000000000;
    double d2 = posit32_tod(p32);
    posit32_t _p32 = posit32_fromd(d);
    printf(" p32.v = %08x\n_p32.v = %08x\n\n d = %.40f\n d2 = %.40f\n", p32.v, _p32.v, d, d2);
}
```

```
notgay:build user$ ./c_api/test/posit/c_api_posit8
 p32.v = b0bfe591
_p32.v = b0bfe591

 d = -3.8126008361577987670898437500000000000000
 d2 = 0.0000000000000000000000000003092334748466
notgay:build user$
```

**Comment by cjdelisle** [comment]
my tests show that `posit8_fromp32()` is also affected by the misinterpretation of the posit32.

**Comment by Ravenwater** [comment]
Closing issue as we are refactoring the library
