### ISSUE TITLE
Compiling programs with mutiple sources returns mutiple definition error.

### ISSUE THREAD

**Issue by SeetharamPandurangi** [stillwater-sc/universal#103]
Trying to compile `main.cpp` `foo.cpp` and `foo2.cpp` gives me this error.

``
CMakeFiles/edu_main.dir/foo.o: In function `sw::unum::ulp(float const&)':
foo.cpp:(.text+0x0): multiple definition of `sw::unum::ulp(float const&)'
CMakeFiles/edu_main.dir/main.o:main.cpp:(.text+0x0): first defined here
CMakeFiles/edu_main.dir/foo.o: In function `sw::unum::ulp(double const&)':
foo.cpp:(.text+0x4a): multiple definition of `sw::unum::ulp(double const&)'
CMakeFiles/edu_main.dir/main.o:main.cpp:(.text+0x4a): first defined here
CMakeFiles/edu_main.dir/foo2.o: In function `sw::unum::ulp(float const&)':
foo2.cpp:(.text+0x0): multiple definition of `sw::unum::ulp(float const&)'
CMakeFiles/edu_main.dir/main.o:main.cpp:(.text+0x0): first defined here
CMakeFiles/edu_main.dir/foo2.o: In function `sw::unum::ulp(double const&)':
foo2.cpp:(.text+0x4a): multiple definition of `sw::unum::ulp(double const&)'
``

Tried compiling the same using g++ and it still throws the same error

``
/tmp/ccaDTIuZ.o: In function `sw::unum::ulp(float const&)':
foo.cpp:(.text+0x0): multiple definition of `sw::unum::ulp(float const&)'
/tmp/ccQBbsJ7.o:main.cpp:(.text+0x0): first defined here
/tmp/ccaDTIuZ.o: In function `sw::unum::ulp(double const&)':
foo.cpp:(.text+0x4a): multiple definition of `sw::unum::ulp(double const&)'
/tmp/ccQBbsJ7.o:main.cpp:(.text+0x4a): first defined here
/tmp/ccOh6lJT.o: In function `sw::unum::ulp(float const&)':
foo2.cpp:(.text+0x0): multiple definition of `sw::unum::ulp(float const&)'
/tmp/ccQBbsJ7.o:main.cpp:(.text+0x0): first defined here
/tmp/ccOh6lJT.o: In function `sw::unum::ulp(double const&)':
foo2.cpp:(.text+0x4a): multiple definition of `sw::unum::ulp(double const&)'
/tmp/ccQBbsJ7.o:main.cpp:(.text+0x4a): first defined here
``

main.cpp
```
#include "posit"

using namespace std;
using namespace sw::unum;	// standard namespace for posits

template<size_t nbits, size_t es>
sw::unum::posit<nbits,es> foo(sw::unum::posit<nbits,es> x);
template<size_t nbits, size_t es>
sw::unum::posit<nbits,es> foo2(sw::unum::posit<nbits,es> x);

int main()
{
	const size_t nbits = 32;
	const size_t es = 2;
	
	posit<nbits, es> s1, s2, s3;

	s1 = 9;        
	s2=foo(s1);
	s3=foo2(s1);
	cout << "s1          : " << setw(3) << s2 << '\n';
	cout << "s2          : " << setw(3) << s3 << '\n';

}
```

foo.cpp
```
#include "posit"

template<size_t nbits, size_t es>
sw::unum::posit<nbits,es> foo(sw::unum::posit<nbits,es> x)
{
	return (x+1);
}
```

foo2.cpp
```
#include "posit"

template<size_t nbits, size_t es>
sw::unum::posit<nbits,es> foo2(sw::unum::posit<nbits,es> x)
{
	return (x-1);
}
```

`g++ -I./universal/posit main.cpp foo.cpp foo2.cpp`

**Comment by Ravenwater** [comment]
@SeetharamPandurangi I am able to reproduce the issue. Working on a fix.

**Comment by Ravenwater** [comment]
@SeetharamPandurangi please try this fix: https://github.com/stillwater-sc/universal/commit/128a079e3692e85d7e684726ef77fbbded99692c

It was an incorrect implementation of template specialization.

**Comment by Ravenwater** [comment]
@SeetharamPandurangi as an aside: the library now follows a root and specialization path for each number system. So your compiler environment should set an include path to the root of whereever you install the Universal code tree, and then refer to the number system of choice: 

#include <universal/posit/posit>

or 

#include <universal/valid/valid>

or 

#include <universal/integer/integer>

etc.

**Comment by SeetharamPandurangi** [comment]
It is working now. Thank you.
