### ISSUE TITLE
Compilation with Clang leads to constexpr errors

### ISSUE THREAD

**Issue by gussmith23** [stillwater-sc/universal#104]
Compiling with Clang 8 on Mac:

```
/Users/gus/universal-llvm/./include/universal/posit/posit.hpp:1732:27: error: constexpr variable 'nbits' must be initialized by a constant expression
        constexpr size_t nbits = number.nbits;
                                 ^~~~~~~~~~~~
/Users/gus/universal-llvm/numerical/thin_triangle.cpp:223:35: note: in instantiation of function template specialization
      'sw::unum::to_binary<sw::unum::posit<32, 2> >' requested here
        ostr << "    a  = " << sw::unum::to_binary(a) << " " << sw::unum::to_base2_scientific(a) << " : " << std::showpos << a << std::noshowpos << std::endl;
                                         ^
/Users/gus/universal-llvm/numerical/thin_triangle.cpp:289:3: note: in instantiation of function template specialization
      'printTriangleConfiguration<sw::unum::posit<32, 2> >' requested here
                printTriangleConfiguration<Posit>(cout, a, b, c);
                ^
```

There are many instances of this same error. Any ideas?

**Comment by Ravenwater** [comment]
It looks like we need to rewrite that code as it is a const variable but for some reason clang doesn't recognizes it as such.

I'll work on this fix now.

**Comment by gussmith23** [comment]
Let me know if you figure this out -- I'm sure it's a clang vs GCC
difference. Curious whether GCC is "smarter" in this case, and is able to
detect that it's constexpr.

Might it be related to the use of templates? That was my initial guess when
I looked at the code.

**Comment by Ravenwater** [comment]
It is the problem of how you pass template arguments down into different processing layers. It may simply be a matter of making the const expr explicit, but I need to do some experimentation with that compiler. I first need to set up that environment before I can attempt the experiments, :-(

**Comment by Ravenwater** [comment]
still haven't been able to set up a clang8 environment, but I have removed the constexpr ambiguity. Can you give it a whirl?

**Comment by gussmith23** [comment]
Thanks Theo! Only just got around to testing it, but you're right, it's fixed.
