### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by xman** [stillwater-sc/universal#11]
Suggest separate work in progress commits into a separate branch. The master branch should keep stable as possible for third-party to compile and try out. From below error messages, I don't find the extract_sign() etc. functions defined. Perhaps the function renaming wasn't complete?

universal.git $ git grep extract_sign
Binary file bin/cmd_dc matches
Binary file bin/cmd_fc matches
Binary file bin/cmd_ieee_fp matches
Binary file bin/cmd_ldc matches
Binary file bin/cmd_pc matches
deprecated/posit/posit_conversion.hpp:          bool _negative = extract_sign(rhs);
deprecated/posit/posit_conversion.hpp:          bool _negative = extract_sign(rhs);
posit/value.hpp:                                                _sign = extract_sign((double)rhs);
tests/posit/extract.cpp:        bool _sign = extract_sign(f);
tests/posit/extract.cpp:        sign = extract_sign(f);
tests/posit/extract.cpp:        sign = extract_sign(f);

$ make
[  1%] Building CXX object tests/float/CMakeFiles/float_quires.dir/quires.cpp.o
In file included from /home/xman/speedgo/projects/sgc/universal.git/tests/float/quires.cpp:15:0:
/home/xman/speedgo/projects/sgc/universal.git/tests/float/../../posit/value.hpp: In member function ‘sw::unum::value<fbits>& sw::unum::value<fbits>::operator=(long double)’:
/home/xman/speedgo/projects/sgc/universal.git/tests/float/../../posit/value.hpp:221:39: error: there are no arguments to ‘extract_sign’ that depend on a template parameter, so a declaration of ‘extract_sign’ must be available [-fpermissive]
       _sign = extract_sign((double)rhs);
                                       ^
/home/xman/speedgo/projects/sgc/universal.git/tests/float/../../posit/value.hpp:221:39: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/xman/speedgo/projects/sgc/universal.git/tests/float/../../posit/value.hpp:222:44: error: there are no arguments to ‘extract_exponent’ that depend on a template parameter, so a declaration of ‘extract_exponent’ must be available [-fpermissive]
       _scale = extract_exponent((double)rhs) - 1;
                                            ^
tests/float/CMakeFiles/float_quires.dir/build.make:62: recipe for target 'tests/float/CMakeFiles/float_quires.dir/quires.cpp.o' failed
make[2]: *** [tests/float/CMakeFiles/float_quires.dir/quires.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'tests/float/CMakeFiles/float_quires.dir/all' failed
make[1]: *** [tests/float/CMakeFiles/float_quires.dir/all] Error 2
Makefile:94: recipe for target 'all' failed

**Comment by xman** [comment]
Commit 9c80b34cda1b08be7709cc246ab2d08e908696df fixed the issue. Thanks.

**Comment by Ravenwater** [comment]
You are absolutely correct, should not have happened, and will not happen again.

**Comment by Ravenwater** [comment]
The commit you referenced fixed the compilation problem, but introduced a bug:

Commit [117e090](https://github.com/stillwater-sc/universal/commit/117e090290b3d4eba502541993eb5cf4235a9f30) fixes the bug
