### ISSUE TITLE
Unable to convert posits to integer.

### ISSUE THREAD

**Issue by SeetharamPandurangi** [stillwater-sc/universal#124]
Compiled using g++  **new.cpp** gives me this error.

**new.cpp: In function ‘int main()’:
new.cpp:12:4: error: cannot convert ‘sw::unum::posit<32, 2>’ to ‘int’ in assignment
  x=a;**

**new.cpp**

       #include "universal/posit/posit"

       int main()
       {

	      sw::unum::posit<32,2> a = 1.2;
	      cout << a << endl;

	      int x;
	      x=a;
	      cout << x << endl;

	      return 0;
       }

g++ new.cpp

Is there a way to convert posit to int ?

**Comment by Ravenwater** [comment]
Yes, all the conversion operators to native types (char,short,int,long,long long, unsigned char, unsigned short, unsigned int, unsigned long, unsigned long long, float, double, long double) are defined as explicit. So you just need to add the conversion operator to your code. 
```
   #include "universal/posit/posit"

   int main()
   {

      sw::unum::posit<32,2> a = 1.2;
      cout << a << endl;

      int x;
      x= int(a);
      cout << x << endl;

      return 0;
   }
```
