### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by DavidMertz** [stillwater-sc/universal#132]
If you want to give me permission to push a feature/bug branch, I can PR this.  I might have some more minor wording cleanup when I review more.

```diff
% git diff master
diff --git a/README.md b/README.md
index c7a46a3..a8d3325 100644
--- a/README.md
+++ b/README.md
@@ -151,7 +151,7 @@ In contrast, the _posit_ number system is designed to be efficient, symmetric, a
 1. **Economical** - No bit patterns are redundant. There is one representation for infinity denoted as ± inf and zero.
 All other bit patterns are valid distinct non-zero real numbers. ± inf serves as a replacement for NaN.
 2. **Mathematical Elegant** - There is only one representation for zero, and the encoding is symmetric around 1.0. Associative and distributive laws are supported through deferred rounding via the quire, enabling reproducible linear algebra algorithms in any concurrency environment.
-3. **Tapered Accuracy** - Tapered accuracy is when values with small exponent have more digits of accuracy and values with large exponents have less digits of accuracy. This concept was first introduced by Morris (1971) in his paper ”Tapered Floating Point: A New Floating-Point Representation”.
+3. **Tapered Accuracy** - Tapered accuracy is when values with small exponent have more digits of accuracy and values with large exponents have fewer digits of accuracy. This concept was first introduced by Morris (1971) in his paper ”Tapered Floating Point: A New Floating-Point Representation”.
 4. **Parameterized precision and dynamic range** -- posits are defined by a size, _nbits_, and the number of exponent bits, _es_. This enables system designers the freedom to pick the right precision and dynamic range required for the application. For example, for AI applications we may pick 5 or 6 bit posits without any exponent bits to improve performance. For embedded DSP applications, such as 5G base stations, we may select a 16 bit posit with 1 exponent bit to improve performance per Watt.
 5. **Simpler Circuitry** - There are only two special cases, Not a Real and Zero. No denormalized numbers, overflow, or underflow.
```

**Comment by Ravenwater** [comment]
Yes, please, edit this as you best see fit and then generate a PR.

Some context that will help you make judgments about edits. The universal library is of February 2020 a very general number system library with arbitrary decimals, integers, fixed-point, linear floating point, posits, and valids, and has a set of tooling to create new number systems quickly. This is currently not reflected in the README. 

Each number system has its use cases and there is a system of adapters to make number system cooperate. I am bringing this up as it is likely that interested folks would likely wanting to jump directly to the number system of interest, and not have to weed through the complexities of number systems they don't care about. For example, the crypto crowd  is likely to want to focus on modulo integer arithmetic, and the DSP crowd on fixed-point and posits, and the numerical analysts on valids. So the readme can really help organize access to the resources available in the library.

And then we have the division between users of the library and developers of the library. I think that we'll have a 100 to 1 ratio between users and developers, so the readme should be optimized for the users, and then have a parallel track for developers.

That is probably more then you signed up for, so start with cleaning up poor English on the current text, and PR that. If you push me hard enough I'll take a stab at creating a better navigation structure, and possibly start a proper wiki.

**Comment by DavidMertz** [comment]
I believe you need to add my permission to push a branch (not master).

**Comment by Ravenwater** [comment]
let's use the gitflow workflow, and you have all the permissions for gitflow
