### ISSUE TITLE
Standard 64bit_posit arithmetic test suite is failing

### ISSUE THREAD

**Issue by Ravenwater** [stillwater-sc/universal#14]
The standard posit<64,3> has a maximum fraction at 1.0 of nbits - sign_bit - 2_region_bits - 3_exponents_bits = 64 - 1 - 2 - 3 = 58 bits. This is more bits than captured by a regular double, and thus doubles can't be used to create golden references.

Unfortunately, different platforms provide different implementations of long double, which creates a lot of gnarly environmental checking, so find the right bits to extract. At this point, something is going wrong, and the test suite is consistently failing on both Windows and Linux (gcc). Windows provides no long double, and Linux gcc 5.4.0 provides an 80bit long double. It does provide a true long double __int128_t implementation, but I haven't been able to investigate how to use this.

However, from a general verification test suite perspective, long doubles would just be a stop gap measure. More appropriately would be to leverage an arbitrary precision floating point library, like MPFR. However, this would create an external dependency that would make the posit lib more difficult to use, so we would like to get at least the posit<64,3> working with native types, and then split out a larger, more comprehensive verification environment that would be using MPFR.

**Comment by Ravenwater** [comment]
This is definitely caused by the reference calculation using IEEE floating point hardware not carrying enough precision through the pipeline. 

We need to go to an MPFR type reference calculation.

**Comment by xman** [comment]
There's no reason why you must bundle MPFR with the library if you are just using it for tests.
For those who don't run the test suites, they should be able to link with just the posit library without the MPFR.

**Comment by Ravenwater** [comment]
The failures currently recorded are caused by the test bench not being able to compute at 112bits of precision. Fixing this will require enhancing the test suite with a multiprecision reference float implementation.

**Comment by Ravenwater** [comment]
The verification functionality will move out of the functional library and will use an arbitrary precision reference.
