### ISSUE TITLE
Wrong return statement

### ISSUE THREAD

**Issue by cmmw** [stillwater-sc/universal#158]
https://github.com/stillwater-sc/universal/blob/dc6d65a9c9dcd183b03ed53822b59db2973841d8/include/universal/blas/vector.hpp#L125

scaledVector should be returned instead of v.

Same here: 

https://github.com/stillwater-sc/universal/blob/dc6d65a9c9dcd183b03ed53822b59db2973841d8/include/universal/blas/vector.hpp#L132

**Comment by Ravenwater** [comment]
@cmmw thanks for the catch, I'll add a regression test to catch this bug.

**Comment by Ravenwater** [comment]
@cmmw Christian, fixed this with latest commit https://github.com/stillwater-sc/universal/commit/e1c7bdcde2b33f1158e6508449acce2dde044f9f
