### ISSUE TITLE
performance improvements: we want a fastPosit sw emulation

### ISSUE THREAD

**Issue by Ravenwater** [stillwater-sc/universal#17]
Right now, the core bit implementation is based on std::bitset<>. Some of the key operators on posits need to be implemented by bit searches in the bitset<>, which is particularly painful for big posits. The current lib runs in the 1MOPS range for small posit, but in the 100KOPS range for big posits.

Looking for help to create a fastPosit implementation that is based on integer arithmetic that will improve performance by several orders of magnitude. Should be a drop-in replacement, so that an application can swap out the two interfaces seamlessly.

**Comment by suiji** [comment]
Will take a closer look at the code to see whether I have anything to offer.  Always enjoy making things go fast.

**Comment by Ravenwater** [comment]
Suiji: had a design review meeting today with the team to discuss the failures caused by the reference calculation done in the test suite. We were comparing different multiprecision approaches and looked at the performance of libraries like GMP and MPFR. They provide MUCH higher performance than Universal, and this is mainly due to their reliance on integer representations of floats instead of our bit representation of posits.

Otherwise stated, performance will come by going to a more efficient representation with respect to the hardware that executes the emulation, i.e. an x86 or ARM processor.

**Comment by Ravenwater** [comment]
I restructured the code to abstract away the underlying register representation, currently std::bitset<>. std::bitset<> was great to experiment with all the bit manipulations necessary to decode and compute with posits. However, std::bitset<> is not computational efficient for arithmetic operations. I have introduced a sw::unum::bitblock<> template class that is to receive a memory and compute efficient alternative. To goal is to get the library up to 100MOPS on a 3GHz x86 for 32bit posits.

**Comment by Ravenwater** [comment]
inefficiency of the posit class is on memory:
sizeof(posit< 8,0>) = 56 bytes
sizeof(posit<16,1>) = 56 bytes
sizeof(posit<32,2>) = 56 bytes
sizeof(posit<64,3>) = 72 bytes

sizeof(regime< 8,0>)   = 16 bytes
sizeof(exponent< 8,0>) = 16 bytes
sizeof(fraction< 8,0>) = 16 bytes
sizeof(regime<32,2>)   = 16 bytes
sizeof(exponent<32,2>) = 16 bytes
sizeof(fraction<32,2>) = 16 bytes

sizeof(bitset<8 >)     = 4 bytes
sizeof(bitset<16>)     = 4 bytes
sizeof(bitset<32>)     = 4 bytes
sizeof(bitset<64>)     = 8 bytes

sizeof(bitblock<8 >)   = 4 bytes
sizeof(bitblock<16>)   = 4 bytes
sizeof(bitblock<32>)   = 4 bytes
sizeof(bitblock<64>)   = 8 bytes

Looks like the standard bitset<> is already pretty efficient. with 32 and 64bit representations being 100% memory efficient. When I started the design of the univeral library and made the decision to use bitset<>, I had this idea in the back of my mind to augment the bitset<> api with arithmetic operators in due time. RIght now, the arithmetic operators are implemented 'on-top' of bitset<> using the bit selection and enumeration apis to manipulate the bits. Looking at that idea again, it might be a good way to bootstrap performance improvements. bitblock<> right now is just a derived class of bitset<> without any augmentation. This could be the hook for experimentation of the arithmetic operators.

**Comment by Ravenwater** [comment]
One of the implementation decisions I ended up making driving towards code complete was to 'cache' the posit decode results. That explains the member variables, regime<>, exponent<>, and fraction<>.  It was good for working with posits as it enables concise expressions to compute arithmetic operators, but as we see above, horrible for memory efficiency. The printing routines also rely heavily on the decoded results to print sign/regime/exponent/fraction information.

In my mind, the goals for performance optimization is to generate a software emulation that is both memory efficient and compute efficient so that it can truly be used as a sw emulation of posit arithmetic. So it is clear from the memory footprint that the decode caching needs to be looked at. Introducing a proxy object that holds the decode state (regime/exponent/fraction) for printing feels like a good idea, as performance for printing is able to absorb the memory inefficiency.

The arithmetic paths, however, are a different story. Right now, add/sub/mul/div all start with a conversion to a (sign,scale,fraction) triplet, which is the vocabulary of the data path. The scale calculation depends on the cached state ( look at the function get_scale() in posit.hpp). That trade-off between memory efficiency and arithmetic performance is the key. I can see that there are much more efficient information caching solutions than the member classes I put together. The computational overhead of having to decode every posit as pre-step in every arithmetic operation appears to be too severe, and thus I think finding an efficient decode caching scheme will be paramount for the performance optimizations.

**Comment by Ravenwater** [comment]
We now have fast implementations of 
posit<4,0>
posit<8,0>
posit<16,1>
posit<32,2>
