### ISSUE TITLE
Specialized posits' to_string must be `inline` 

### ISSUE THREAD

**Issue by thorsten-ottosen** [stillwater-sc/universal#226]
The problem is with e.g.

```
   std::string to_string(const posit<NBITS_IS_8, ES_IS_0>& p, std::streamsize precision);

```
This may lead to linker errors if headers are included in more than one translation unit.

**Comment by Ravenwater** [comment]
[commit](https://github.com/stillwater-sc/universal/commit/bb3e8a6e821027d7b6bd5b639b2c5e56b3b8ceb0) fixes this

**Comment by Ravenwater** [comment]
Today we renamed the default branch to `main`, and this commit ended up in the new `main` branch.
