### ISSUE TITLE
Initializing posit with long double yields incorrect representation

### ISSUE THREAD

**Issue by lvandam** [stillwater-sc/universal#24]
When I try to initialize a posit (nbits = 32, es = 2) with a value cast as long double, the representation when printed is not close to the actual initial value.
```
posit<32, 2> E_pos((long double)0.79432823472428150206586100479);
cout << setprecision(30) << fixed << E_pos << endl;
cout << pretty_print(E_pos)  << endl;
```
**Output**
```
0.500071857124567031860351562500
s0 r01 e11 f000000000000100101101011001 qSE v0.50007185712456703
```

Part of the fraction bits ("100101101011001") seems to be correct, but the closest representation should have this part shifted to the left by 12 positions.

```
100101101011001000110000110 // fbits correct representation
000000000000100101101011001 // fbits actual representation
```

Is this a bug, or a mistake in my small example? Would love to know.

Cheers,
Laurens

**Comment by Ravenwater** [comment]
thanks for doing this test. Let me take a closer look

           *Dr. E. Theodore L. Omtzigt*

CEO and Founder

Stillwater Supercomputing, Inc.



East Coast Office : (617) 314 6424

West Coast Office: (415) 738 7387

Mobile phone #  : (916) 296-7901

3941 Park Drive, Suite 20-354

El Dorado Hills, CA 95762

**Comment by Ravenwater** [comment]
You found a bug. Working on a fix right now.

**Comment by lvandam** [comment]
I'm working with GCC 7.2.0 (Mac, i5).
```
$ g++-7 --version
g++-7 (Homebrew GCC 7.2.0_1) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Ravenwater** [comment]
Laurens: please try latest commit ea5c4f6

GCC on my system represents long double as an 80bit extended format. I had incorrectly set the size of the fraction: turns out that x87 only carries 63bits of fraction.

There is no code yet to extract the fraction of long doubles that are true quad precision floats.

Please let me know if this solves your issue.

**Comment by lvandam** [comment]
Thanks Theodore, it seems that the issue has been resolved.
