### ISSUE TITLE
Fixpoint type does not support creation of complex numbers

### ISSUE THREAD

**Issue by mmoelle1** [stillwater-sc/universal#243]
The `fixpnt` type lacks a file `math/complex.hpp` (as it is available for posits and cfloats) with the functionality to create complex numbers, e.g., by providing real and imaginary parts.

Thanks for fixing this,
Matthias

**Comment by Ravenwater** [comment]
@mmoelle1 release v3.34.1 added a math library for the fixpnt number system, including a complex.hpp with real(), imag(), and conj() functions.

https://github.com/stillwater-sc/universal/releases/tag/v3.34.1

Let me know if this solves your use case.

**Comment by Ravenwater** [comment]
@mmoelle1 has this issue been resolved for application?

**Comment by Ravenwater** [comment]
According to the C++ ISO spec, §26.2/2:

The effect of instantiating the template complex for any type other than float, double or long double is unspecified.

This would indicate that this is not a bug, but requires a custom implementation of complex<> for fixed-points.
