### ISSUE TITLE
Posit convert function extra bit used?

### ISSUE THREAD

**Issue by jeffreyyu0602** [stillwater-sc/universal#274]
I looked into the source code of arbitrary length posit implementation (universal/include/universal/number/posit/posit_impl.hpp) and the pt_len variable is declared as nbits + 3 + es. All the bitblocks are created using this length. I did some testing and found that there is always one bit left unused. For this specific implementation, only an extra fraction bit and a sticky bits are used. Why it is declared as nbits + 3 + es? I am wondering if this one bit can be saved even though it won't lead to much improvement in performance if there is any. Thanks!
```
constexpr size_t pt_len = nbits + 3 + es;
bitblock<pt_len> pt_bits;
bitblock<pt_len> regime;
bitblock<pt_len> exponent;
bitblock<pt_len> fraction;
bitblock<pt_len> sticky_bit;
```

**Comment by Ravenwater** [comment]
@jeffreyyu0602 excellent question. An empirical check would be to remove the bit and do the regression runs and confirm your hypothesis.

**Comment by Ravenwater** [comment]
Need to revisit in refactoring of posit class in v4.
