### ISSUE TITLE
Incorrect behavior of rounding float to posit

### ISSUE THREAD

**Issue by dingjr27** [stillwater-sc/universal#277]
Dear developer,

When i tried to round 0.000601383f to posit<8,1>, the universal library gives 0.000976562f, which is 0b00000010 in posit. However i realized 0.000244141f should be the correct number, which is 0b00000001 in posit. Because 0.000976562 - 0.000601383 = 3.75e-4 while 0.000601383 - 0.000244141 = 3.57e-4, which is closer to 0.000601383f.

Same thing observed for 2298.67f and around number. The universal library gives 4096, but 1024 may be a better choice.

Best Regards!

**Comment by Ravenwater** [comment]
@dingjr27 thanks for filing this issue.

What you are observing is geometric rounding. In the exponential regions of the posit sampling you are rounding exponent bits, not fraction bits, so the 'rounding middle` is the geometric average between adjacent samples.

Here is the sampling of posit<8,1> around your value of 0.000601383f:

posit<8,1> 0.0000001..    0.000244141   <- all regime bits, no exponent, no fraction
posit<9,1> 0.0000001.1.  0.000488281   <- 1 exponent bit
                                                                <------- sample 0.000601383 0b0.01110100.00111011010011000100001
posit<8,1> 0.000001.0.   0.000976562    <- 1 exponent bit created by rounding
posit<9,1> 0.000001.0.1  0.00146484     <- 1 exponent bit and 1 fraction bit 

The values of a posit<9,1> will overlap the values of a posit<8,1> when the LSB is 0, and present the mid-point between posit<8,1> samples when the LSB is 1.  So posit<9,1> is an easy 'visualization' where a value falls in the rounding decision: if the value is above the midpoint, it is rounded up. If it is below the midpoint, it is rounded down. This rounding is implicit by the virtue of rounding exponent bits.

Let me know if that explained the rounding behavior of posits for you.

**Comment by dingjr27** [comment]
Thanks for your kind explanation, this solved my question.
