### ISSUE TITLE
Posit equivalent of nextafter() or nexttoward()

### ISSUE THREAD

**Issue by mlaass** [stillwater-sc/universal#280]
I am quite fresh to Posits, maybe someone can help me with this:
For floating points, the standard library has the `nextafterf( float from, float to )` function, which gives me the next bigger or smaller floating-point value from the first parameter toward the second parameter.
I am looking for an equivalent of this function for Posits. 
How would I go about this? 
For the problem I'm trying to solve, it would already suffice to know the size of the interval towards the next bigger number.

**Comment by mlaass** [comment]
Found it!

**Comment by Ravenwater** [comment]
@mlaass :-) so you found the nextafter/nexttowards templated functions that take a posit. In general, all number systems will have a standard library interface, as to enable true plug-in replacements of the native types.

as you can see from the implementation:
```
template<size_t nbits, size_t es>
posit<nbits,es> nextafter(posit<nbits,es> x, posit<nbits, es> target) {
	if (x == target) return target;
	if (target.isnar()) {
		if (x.isneg()) {
			--x;
		}
		else {
			++x;
		}
	}
	else {
		if (x > target) {
			--x;
		}
		else {
			++x;
		}
	}
	return x;
}
```

we are overloading the prefix increment and decrement operators for Real types to give you an one ULP progression. So if you are doing ULP work operator++/--() can be very useful. There is also an ulp() method that gives you back the ULP directly.

For many of our internal research we use the progression fixpnt<>/cfloat<>/posit<> for many of our comparisons, and we work hard to make the API for all these number systems identical. If you find they are lacking, please let us know and we'll fix it.
