### ISSUE TITLE
Matrix equality (==) operator

### ISSUE THREAD

**Issue by jamesquinlan** [stillwater-sc/universal#307]
The overloaded operator == returns incorrect results.  As a test case:

`sw::universal::blas::matrix<double>  A = {
        { 5.0,    1.0,   0.0,   3.0}, 
	{ 0.0,  -7.0,  -1.0,  -5.0},
	{ 0.0,  -4.0,  -8.0,  -7.0},
	{ 0.0,   3.0,   3.0,   12.0 } 
};`

`std::cout << ((inv(A)*A) == I)  << std::endl;`

where `I` is the 4x4 identity matrix, returns false.  

Others (e.g., MATLAB) have same issue due to rounding.  Perhaps a better approach is to include a tolerance, that is equal within epsilon.

**Comment by Ravenwater** [comment]
Operator==() should retain its simple definition of comparing the bit patterns of lhs and rhs and only return true if the bit patterns are identical. For vector, matrix, and tensor equality in the numerical sense, we would need to define some distance metric, and thus there are many different interpretations of equality. operator==() doesn't have any parameterization to capture that state space and thus isn't the right function to overload.

We should add vector, matrix, and tensor equality measures as a separate set of functions that can capture the distance measure used to measure equality.
