### ISSUE TITLE
bfloat implementation

### ISSUE THREAD

**Issue by RaulMurillo** [stillwater-sc/universal#362]
Navigating through the source code, I found 2 different implementations of the Google Brain floating point format. One is a specialization of cfloat (https://github.com/stillwater-sc/universal/blob/e6ef6d76d2012c0261c6b480a37b78b30470d419/include/universal/number/cfloat/cfloat.hpp#L97C7-L97C13), while the other is defined as an independent number format (https://github.com/stillwater-sc/universal/tree/main/include/universal/number/bfloat).
Also, I came out with different execution results.

What are the main differences between both implementations? 
And which one should I use to simulate the original Bfloat type?

**Comment by Ravenwater** [comment]
@RaulMurillo the intent of the specialized bfloat16 is to have a fast bfloat16 that is emulated through the native FP32. The cfloat<> parameterization contains all the special formats used in DL, and the type bfloat_t is a type alias for the particular cfloat configuration.

I initially thought that bfloat16 didn't have subnormals, but it appears that it has, so I updated the bfloat_t type alias.

As bfloat16 is a lowering through single precision IEEE-754, I do not have a regression suite testing it. The details of how the special encodings are handled need to be gathered.

**Comment by Ravenwater** [comment]
@RaulMurillo 

use *bfloat16* in any performance-sensitive code. The storage is a fixed _uint16_t_ and the arithmetic operators will use the floating-point hardware.

use *bfloat_t* in comparison codes that are evaluating mixed-precision algorithms and optimizations. *bfloat_t* is a type alias to a specific _cfloat<16,8,uint16_t, true, false, false>_ type, which emulates floating point arithmetic with integers, and is will be slower but integrate better with conversions to bigger and smaller _cfloats_ as that functionality is provided in the _cfloat_ type.


NOTE: there is a bug in the *bfloat* implementation when assigning a native ieee-754 floating-point that contains a signalling NaN. That will get converted to a quiet NaN. Fixing this will cut the performance in half and make the _constexpr_ code much more complicated, so not attractive.
