### ISSUE TITLE
Arithmetic with posits

### ISSUE THREAD

**Issue by mmoelle1** [stillwater-sc/universal#37]
Dear developers of universal,

we are developing a fully templated simulation package for the numerical solution of PDE problems that would allow to test the arithmetic performance of unums/posits for realistic applications.

Does universal support the 'standard' numerical functions like std::sin, std::cos, ... next to the binary operators +,-,/,*?

Kind regards,
Matthias

**Comment by Ravenwater** [comment]
Hi Matthias:

Short answer is not yet, but tell us what you need and we will make it so. John Gustafson has been experimenting with different posit/quire configurations to implement these functions efficiently, so the math has been worked out, we just have been looking for an effort like yours to get started on the implementation.

On a side note, the hardware experiments for FPGAs have been exploring 25/26/27 bit posits to replace 32-bit floats in Krylov solvers. Love to learn more about your approach, so we can possibly pull in the hardware.

**Comment by Ravenwater** [comment]
I have added transcendental and hyperbolic function implementations and test suites.

This uses IEEE doubles so these are not native posit implementations and the results will exhibit the same limitations as IEEE doubles have. Otherwise stated, at posit configurations around 56 bits and higher, the additional accuracy of the posit significant will not be reflected in the function values.

**Comment by Ravenwater** [comment]
To bootstrap you quickly on using the functions they are in the namespace sw::unum:: and follow the same function names as std::

// exponential functions
sw::unum::exp(posit)
sw::unum::exp2(posit)

// general power function
sw::unum::pow(posit, posit)

// logarithmic functions
sw::unum::log(posit)
sw::unum::log2(posit)
sw::unum::log10(posit)

// trigonometric functions
sw::unum::sin(posit)
sw::unum::cos(posit)
sw::unum::tan(posit)
sw::unum::asin(posit)
sw::unum::acos(posit)
sw::unum::atan(posit)

// hyperbolic functions
sw::unum::sinh(posit)
sw::unum::cosh(posit)
sw::unum::tanh(posit)
sw::unum::asinh(posit)
sw::unum::acosh(posit)
sw::unum::atanh(posit)

**Comment by Ravenwater** [comment]
We stubbed the functions for the moment going through a posit -> double -> posit conversion to finish software integration.

Posit-native function libraries are in process.
