### ISSUE TITLE
posit color print has additional 2's complement

### ISSUE THREAD

**Issue by Sylvexia** [stillwater-sc/universal#444]
https://github.com/stillwater-sc/universal/blob/77d12303876615efeb500dd58543100681aaf9c7/include/universal/number/posit/manipulators.hpp#L260-L269
This has additional 2's complement.
Which cause the negative fraction has additional 2's complement
Which does not comply with posit standard.

example:
`/build/tools/cmd/posit -31`

posit<32,2>  = 11100000010000000000000000000000 : -31

With posit standard it should be:
```
1 110 00 00010000000000000000000000 ->
1 110 00 11110000000000000000000000
```

**Comment by Ravenwater** [comment]
@Sylvexia thank you for reporting this. Let me generate a correct table for your review.

**Comment by Ravenwater** [comment]
![image](https://github.com/user-attachments/assets/b30c1de6-7d86-4b41-bb13-951b0127d106)

@Sylvexia please review

**Comment by Ravenwater** [comment]
fixed with commit https://github.com/stillwater-sc/universal/commit/e6f1e625fdb5106d932406a0c66f7a964d13acdc
