### ISSUE TITLE
Multiplication and division give incorrect results

### ISSUE THREAD

**Issue by xman** [stillwater-sc/universal#5]
[runposit.cpp.txt](https://github.com/stillwater-sc/universal/files/1525505/runposit.cpp.txt)
$ ./runposit 
3.400000 + 5.700000 => 9.100000
3.400000 - 5.700000 => -2.300000
3.400000 * 5.700000 => 9.690000
3.400000 / 5.700000 => 0.334688

**Comment by Ravenwater** [comment]
The culprit is the rounding/conversion logic, and this is a known issue. We are missing a correct rounding equation that survives the parameterization. We have been looking at this problem for awhile, and any help would be appreciated.

**Comment by Ravenwater** [comment]
multiplication has been passing. Division is still being implemented. The bug resided in the posit conversion of the arithmetic result.
