### ISSUE TITLE
posit<4,0> does not compare correctly

### ISSUE THREAD

**Issue by xman** [stillwater-sc/universal#60]
The posit<4,0> does not compute comparisons correctly.

For example,
1.5 < -4 returns true,
-0.5 < 0 returns false.

**Comment by Ravenwater** [comment]
Which version: specialized or unspecialized?

**Comment by xman** [comment]
Tested on current master branch. Commit hash: 1dea12c546749e9b8d76bfaba7062ff1c889ab3a

**Comment by Ravenwater** [comment]
You found a verification test hole: it is not the comparisons that are to blame, it is the integer conversion. The conversion verification suite only tested the float/double/long double code path.

I need to figure out how to create an integer conversion reference to make certain this code path is covered as well. 

I was not able to reproduce your -0.5 < 0 is false failure. I need more contextual code to see what path you are hitting.

If you are stuck behind this bug, simply change your assignment using a float.

**Comment by xman** [comment]
See if you can reproduce with this test program.

https://gist.github.com/xman/f3d1860c641d6e6c1ef7b0ba37149d2a#file-runpositn4e0-cpp

**Comment by Ravenwater** [comment]
that code passes on my build, except of course for your erroneous handling of NaR. Your gist is following the IEEE ordering and not the posit ordering.

I added an integer conversion verification test suite to plug the integer conversion test hole you found. Running regressions now.

**Comment by Ravenwater** [comment]
@xman checked in the bug fix: https://github.com/stillwater-sc/universal/commit/896c265748f351d411034869364e226ab29736fa

Please confirm if this resolves your issue.

**Comment by xman** [comment]
Thanks. It resolves the issue.

**Comment by xman** [comment]
I believe the issue was with the specialized code for posit<4,0>. Not urgent for me now, but you may like to check when you have time to run with -DPOSIT_FAST_SPECIALIZATION.
