### ISSUE TITLE
mac compilation problem

### ISSUE THREAD

**Issue by akorzh** [stillwater-sc/universal#64]
trying build on mac / clang etc.
complains about popcntl, ctzl and __N
can you hint where those should normally come from? tried searching but failed to find so far

**Comment by akorzh** [comment]
ok __clang__ should be __CLANG__ which fixes popcntl/ctzl issue but __N still remains

**Comment by Ravenwater** [comment]
@akorzh these are intrinsics that where introduce with the new bitblock implementation. We did not do a full sweep of all the compiler environments to bring that back to working order. 


Need to figure out what the __N means. Pulling in Mark.

**Comment by akorzh** [comment]
also looks like needed to add -fms-extensions to let it accept __try constructs (https://clang.llvm.org/docs/MSVCCompatibility.html) though SEH support is partial in clang/llvm.

still puzzled by __N (grep and webseasrch gave me nothing so far)

this is my output so far (after changin __clang__ to __CLANG__ and __APPLE__) and adding -fms-extensions:

/Users/anton/posit/universal/./posit/../bitblock/ubb.h:704:28: error: use of undeclared identifier '__N'
                                __throw_overflow_error(__N("BaseBitset::M_do_to_ulong"));
                                                       ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:716:28: error: use of undeclared identifier '__N'
                                __throw_overflow_error(__N("BaseBitset::M_do_to_ullong"));
                                                       ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:720:5: warning: shift count >= width of type [-Wshift-count-overflow]
                                << UBB_BITS_PER_WORD);
                                ^  ~~~~~~~~~~~~~~~~~
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:1393:31: error: use of undeclared identifier '__N'
                                        __throw_out_of_range_fmt(__N("bitset::bitset: position "
                                                                 ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:1410:31: error: use of undeclared identifier '__N'
                                        __throw_out_of_range_fmt(__N("%s: position (which is %zu) "
                                                                 ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:1596:26: error: use of undeclared identifier '__N'
                                        __throw_logic_error(__N("bitset::bitset(const _CharT*, ...)"));
                                                            ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:2186:31: error: use of undeclared identifier '__N'
                                        __throw_invalid_argument(__N("bitset::M_copy_from_ptr"));
                                                                 ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:2270:5: warning: extension used [-Wlanguage-extension-token]
                                __try
                                ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:2299:5: error: expected '__except' or '__finally' block
                                __catch(__cxxabiv1::__forced_unwind&)
                                ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:2299:13: error: use of undeclared identifier '__cxxabiv1'
                                __catch(__cxxabiv1::__forced_unwind&)
                                        ^
/Users/anton/posit/universal/./posit/../bitblock/ubb.h:2299:41: error: expected expression
                                __catch(__cxxabiv1::__forced_unwind&)

**Comment by suiji** [comment]
Working pre-ubb versions can be built by checking out older releases.

In the meantime, let me get about replacing the system-specific exceptions with something more generic.  These are vestiges of the early <bitblock> implementation.

**Comment by akorzh** [comment]
Hey actually got it to work by heavy hacking ( probably got some stuff broken) but definitely no need for old code.
FYI here is my patch

**Comment by Ravenwater** [comment]
just in case you need it:

git checkout 28921dad99a6349afd3836aeb7f5f72d0df16076


that commit is the version before the bitblock modifications. It is on me
that I didn't tag that version before we merged in such a big change.

           *Dr. E. Theodore L. Omtzigt*

CEO and Founder

Stillwater Supercomputing, Inc.



East Coast Office : (617) 314 6424

West Coast Office: (415) 738 7387

Mobile phone #  : (916) 296-7901

3941 Park Drive, Suite 20-354

El Dorado Hills, CA 95762

**Comment by Ravenwater** [comment]
MacOS builds are now part of the regular flow, although not in CodeShip CI, so still manual. By backing out the bitblock implementation, we have gotten a stable code base again. Closing for now.
