### ISSUE TITLE
Need help with builds on a collection of compilers (Intel, CLang, Apple, ARM, etc.)

### ISSUE THREAD

**Issue by Ravenwater** [stillwater-sc/universal#8]
We don't have Apple gear to build on, so I am looking for folks that can keep a Mac build clean.
We don't have Intel compiler gear, so I am looking for folks that can keep an Intel build clean.
We do have ARM gear, so in this case, looking for collaborators to try to set up a cross compilation flow.

**Comment by RobLewis** [comment]
I'm new to this. I have a Mac. What's involved in keeping a build clean?

**Comment by Ravenwater** [comment]
Hi Rob: thanks for the inquiry. 

The task would be to pull master, build the test suite and example programs (that is, > mkdir build;cd build;cmake ..;make; ctest -j 8) and validate that all the code is compiling and all the tests are running, and the results are similar to the other builds, and reporting any issues, or better yet, resolve any issues, so that Mac developers have access to this library in a quality manner as well.

The current state is that the test suites for posit-48bit and posit-64bit report failures, but that is actually caused by the testbench not having enough precision to validate that size posit. The approach to solve these failures is to have a 128bit floating point capability that is portable across the different platforms.

Here is the output of the validation tests on my system (A Windows 10 box running VS2017);

> 1>------ Build started: Project: RUN_TESTS, Configuration: Release x64 ------
> 1>Test project C:/Users/tomtz/Documents/dev/universal/build
> 1>      Start  1: float_quire_accumulation
> 1> 1/61 Test  #1: float_quire_accumulation .........   Passed    0.02 sec
> 1>      Start  2: float_quires
> 1> 2/61 Test  #2: float_quires .....................   Passed    0.02 sec
> 1>      Start  3: unum_construct
> 1> 3/61 Test  #3: unum_construct ...................   Passed    0.01 sec
> 1>      Start  4: unum2_construct
> 1> 4/61 Test  #4: unum2_construct ..................   Passed    0.01 sec
> 1>      Start  5: bitblock_arithmetic
> 1> 5/61 Test  #5: bitblock_arithmetic ..............   Passed    0.15 sec
> 1>      Start  6: bitblock_logic
> 1> 6/61 Test  #6: bitblock_logic ...................   Passed    0.05 sec
> 1>      Start  7: posit_128bit_posit
> 1> 7/61 Test  #7: posit_128bit_posit ...............   Passed    0.02 sec
> 1>      Start  8: posit_16bit_posit
> 1> 8/61 Test  #8: posit_16bit_posit ................   Passed   13.00 sec
> 1>      Start  9: posit_32bit_posit
> 1> 9/61 Test  #9: posit_32bit_posit ................   Passed   12.39 sec
> 1>      Start 10: posit_48bit_posit
> 1>10/61 Test #10: posit_48bit_posit ................***Failed   17.58 sec
> 1>      Start 11: posit_64bit_posit
> 1>11/61 Test #11: posit_64bit_posit ................***Failed   17.20 sec
> 1>      Start 12: posit_8bit_posit
> 1>12/61 Test #12: posit_8bit_posit .................   Passed    0.47 sec
> 1>      Start 13: posit_arithmetic_add
> 1>13/61 Test #13: posit_arithmetic_add .............   Passed    0.64 sec
> 1>      Start 14: posit_arithmetic_divide
> 1>14/61 Test #14: posit_arithmetic_divide ..........   Passed    0.89 sec
> 1>      Start 15: posit_arithmetic_fma
> 1>15/61 Test #15: posit_arithmetic_fma .............   Passed    0.02 sec
> 1>      Start 16: posit_arithmetic_literals
> 1>16/61 Test #16: posit_arithmetic_literals ........   Passed    4.52 sec
> 1>      Start 17: posit_arithmetic_multiply
> 1>17/61 Test #17: posit_arithmetic_multiply ........   Passed    0.66 sec
> 1>      Start 18: posit_arithmetic_negate
> 1>18/61 Test #18: posit_arithmetic_negate ..........   Passed    0.11 sec
> 1>      Start 19: posit_arithmetic_reciprocate
> 1>19/61 Test #19: posit_arithmetic_reciprocate .....   Passed    0.53 sec
> 1>      Start 20: posit_arithmetic_sqrt
> 1>20/61 Test #20: posit_arithmetic_sqrt ............   Passed    0.02 sec
> 1>      Start 21: posit_arithmetic_subtract
> 1>21/61 Test #21: posit_arithmetic_subtract ........   Passed    0.63 sec
> 1>      Start 22: posit_assignment
> 1>22/61 Test #22: posit_assignment .................   Passed    0.02 sec
> 1>      Start 23: posit_conversion
> 1>23/61 Test #23: posit_conversion .................   Passed    1.28 sec
> 1>      Start 24: posit_conversion_functions
> 1>24/61 Test #24: posit_conversion_functions .......   Passed    0.02 sec
> 1>      Start 25: posit_decode
> 1>25/61 Test #25: posit_decode .....................   Passed    0.02 sec
> 1>      Start 26: posit_decrement
> 1>26/61 Test #26: posit_decrement ..................   Passed    0.02 sec
> 1>      Start 27: posit_increment
> 1>27/61 Test #27: posit_increment ..................   Passed    0.02 sec
> 1>      Start 28: posit_logic
> 1>28/61 Test #28: posit_logic ......................   Passed    0.38 sec
> 1>      Start 29: posit_postfix
> 1>29/61 Test #29: posit_postfix ....................   Passed    0.02 sec
> 1>      Start 30: posit_prefix
> 1>30/61 Test #30: posit_prefix .....................   Passed    0.02 sec
> 1>      Start 31: posit_quire_accumulation
> 1>31/61 Test #31: posit_quire_accumulation .........   Passed    0.76 sec
> 1>      Start 32: posit_quires
> 1>32/61 Test #32: posit_quires .....................   Passed    0.02 sec
> 1>      Start 33: posit_reciprocal_tables
> 1>33/61 Test #33: posit_reciprocal_tables ..........   Passed    0.02 sec
> 1>      Start 34: valid_arithmetic_add
> 1>34/61 Test #34: valid_arithmetic_add .............   Passed    0.01 sec
> 1>      Start 35: cmd_dc
> 1>35/61 Test #35: cmd_dc ...........................   Passed    0.02 sec
> 1>      Start 36: cmd_fc
> 1>36/61 Test #36: cmd_fc ...........................   Passed    0.02 sec
> 1>      Start 37: cmd_ieee_fp
> 1>37/61 Test #37: cmd_ieee_fp ......................   Passed    0.02 sec
> 1>      Start 38: cmd_ldc
> 1>38/61 Test #38: cmd_ldc ..........................   Passed    0.02 sec
> 1>      Start 39: cmd_numeric_limits
> 1>39/61 Test #39: cmd_numeric_limits ...............   Passed    0.02 sec
> 1>      Start 40: cmd_pc
> 1>40/61 Test #40: cmd_pc ...........................   Passed    0.02 sec
> 1>      Start 41: edu_basic_operators
> 1>41/61 Test #41: edu_basic_operators ..............   Passed    0.03 sec
> 1>      Start 42: edu_components
> 1>42/61 Test #42: edu_components ...................   Passed    0.02 sec
> 1>      Start 43: edu_discretization_curves
> 1>43/61 Test #43: edu_discretization_curves ........   Passed    0.02 sec
> 1>      Start 44: edu_enumeration
> 1>44/61 Test #44: edu_enumeration ..................   Passed    0.02 sec
> 1>      Start 45: edu_exponents
> 1>45/61 Test #45: edu_exponents ....................   Passed    0.01 sec
> 1>      Start 46: edu_extract
> 1>46/61 Test #46: edu_extract ......................   Passed    0.02 sec
> 1>      Start 47: edu_fractions
> 1>47/61 Test #47: edu_fractions ....................   Passed    0.07 sec
> 1>      Start 48: edu_raw_bit_patterns
> 1>48/61 Test #48: edu_raw_bit_patterns .............   Passed    0.02 sec
> 1>      Start 49: edu_regimes
> 1>49/61 Test #49: edu_regimes ......................   Passed    0.02 sec
> 1>      Start 50: edu_rounding
> 1>50/61 Test #50: edu_rounding .....................   Passed    0.03 sec
> 1>      Start 51: edu_scales
> 1>51/61 Test #51: edu_scales .......................   Passed    0.02 sec
> 1>      Start 52: edu_tables
> 1>52/61 Test #52: edu_tables .......................   Passed    0.05 sec
> 1>      Start 53: edu_values
> 1>53/61 Test #53: edu_values .......................   Passed    0.03 sec
> 1>      Start 54: blas_l1_asum
> 1>54/61 Test #54: blas_l1_asum .....................   Passed    0.02 sec
> 1>      Start 55: blas_l1_axpy
> 1>55/61 Test #55: blas_l1_axpy .....................   Passed    0.03 sec
> 1>      Start 56: blas_l1_dot
> 1>56/61 Test #56: blas_l1_dot ......................   Passed    0.06 sec
> 1>      Start 57: blas_l1_fused_dot
> 1>57/61 Test #57: blas_l1_fused_dot ................   Passed    0.03 sec
> 1>      Start 58: blas_l2_mv
> 1>58/61 Test #58: blas_l2_mv .......................   Passed    0.03 sec
> 1>      Start 59: blas_l3_lu_decomposition
> 1>59/61 Test #59: blas_l3_lu_decomposition .........   Passed    0.04 sec
> 1>      Start 60: dsp_fir_filter
> 1>60/61 Test #60: dsp_fir_filter ...................   Passed    0.02 sec
> 1>      Start 61: playground_skeleton
> 1>61/61 Test #61: playground_skeleton ..............   Passed    0.02 sec
> 1>
> 1>97% tests passed, 2 tests failed out of 61
> 1>
> 1>Total Test time (real) =  72.46 sec
> 1>
> 1>The following tests FAILED:
> 1>	 10 - posit_48bit_posit (Failed)
> 1>	 11 - posit_64bit_posit (Failed)
> 1>Errors while running CTest

**Comment by RobLewis** [comment]
Thanks. I spent some time trying to build the project in Eclipse (Mac), with no success. Among other errors, I'm seeing "No rule to make target `all'" when trying to build the project. I have very little experience using Eclipse for C++, so any tips on getting it going would be appreciated. 
I downloaded the GitHub repository to my local machine and imported it into a new project, but am unable to build it.

**Comment by Ravenwater** [comment]
Looks like Eclipse has some issues with CMake integration:
https://cmake.org/Wiki/Eclipse_CDT4_Generator

**Comment by lvandam** [comment]
Rob,

I highly recommend using CLion (by Jetbrains) on a Mac. It has native CMake support. In fact, when creating a CLion project a CMake project is created automatically. Importing the Universal repository in CLion might work by making only a few to no modifications at all.

**Comment by RobLewis** [comment]
Thanks @lvandam  A co-worker has been struggling with the same issue using CLion on Windows, with Cygwin. Any tips on that environment?

**Comment by RobLewis** [comment]
I was able to build and test the project on the Mac, using just the Terminal. All 61 tests passed.

**Comment by RobLewis** [comment]
Also tried the `ctest -j 8` command and again, all 61 tests reported passing. (I presume this uses 8 threads; it did make the fans on my MacBook Pro kick in :)

**Comment by Ravenwater** [comment]
Good to hear that the CLI works on a Macbook without trouble.

Yesterday, when I built the CI/CD integration I fixed the failing tests, so that the CI would show a green build.

ctest -j 8 indeed executes on 8 cores. I am glad it is making your Macbook work

On Windows, you should just use Visual Studio, use the Community edition if you don't want to pay; the source code navigation features are superb and pay for the cost of that tool chain within a month. The nice thing about VS is that it does have CMake integration.

**Comment by Ravenwater** [comment]
Since we now have a Docker container mechanism for CI/CD, this problem has progressed to creating different containers for each of the different compiler environments, combined with some README engineering to report on the status.

**Comment by Ravenwater** [comment]
@mmoelle1 has been adding different compilers and platforms he has available in Delft University of Technology.
