### ISSUE TITLE
Building without c++14 support

### ISSUE THREAD

**Issue by Tongdongq** [stillwater-sc/universal#86]
I am working on an older machine that uses gcc 4.8 (without c++14). I do not have admin rights to upgrade, is there an easy way to run it without c++14?

**Comment by Ravenwater** [comment]
yes, fortunately there is.
Go into the CMakeLists.txt in the root and find line 426:
426:     set(EXTRA_C_FLAGS "${EXTRA_C_FLAGS} /Zc:__cplusplus /std:c++14")
just comment that out, regenerate the makefiles with cmake, and the lib and its test programs compile. Of course, I have only tested this with gcc 7.3, so I don't know if I have really reproduced your environment. 

Please report your findings if this is a work-around or not.

**Comment by Tongdongq** [comment]
It seems to work. I actually changed line 234 'set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")'
I do get a ton of errors for single quotes as separators in integer constants, which were introduced in c++14: https://en.cppreference.com/w/cpp/language/integer_literal
I seem to have fixed it by executing 'find . -name *".hpp" -exec sed -i "s/0x.*'/0x.*/g" {} \;' in the root (USE AT OWN RISK).

Also two tests fail: playground_gismo_test and playground_serialization.
Gismo produces a runtime regex error, which is likely to originate from parse() at posit/posit.hpp:489. My GCC 4.8 apparently does not have a full <regex> implementation.
Looking at the code of serialization.cpp, I think this error has the same cause.

**Comment by Ravenwater** [comment]
then you are in business. The constants for large posits are huge, so the single quotes to make them readable are the source of that.

the lib is not dependent on gismo playground applications which are just example programs that we used to find all the issues that integration with G+SMO covered. 

The regex error has been reported before by LLNL folks. Serialization using the posit format depends on it. If you serialize using long doubles you could comment this code out to get the compilation succeed.
