### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tongdongq** [stillwater-sc/universal#89]
Is there any API documentation? It's a bit of a drag looking through the code to go through the code of the Posit class, especially since there is no division between source and header.

**Comment by Ravenwater** [comment]
The API is the arithmetic constructs of the C++ language: the universal library is a complete arithmetic engine that elevate arbitrary posits to the level of native types of the language. 

So wherever you use a float or a double you can use a posit<nbits,es> and all will work verbatim but now in posit arithmetic.

The best way to use types in C++ is to create a Scalar type and parameterize on that type. Then when you want to change the type all you need to do is change the Scalar type, as in this snippet:

// parameterize with respect to the Scalar type
template<typename Scalar>
Scalar MyFunction(Scalar a, Scalar b) {
    Scalar c;
    c = (2*a + b/7.12345e-7f) * (a*b);
    return c;
}

int main() {

   using Scalar = float;
   // using Scalar = sw::unum::posit<20,1>;
   ...
   Scalar a, b;
   a = 6.3;
   b = 9.1;
   MyFunction(a, b);
   ...
}

**Comment by Tongdongq** [comment]
Does using sw::unum::posit automatically use quires?

**Comment by Ravenwater** [comment]
The posit type only represents the data and its arithmetic. The quire type represents the super-accumulator and its arithmetic. There are two instructions that are used to connect posit arithmetic to the quire: quire_add(posit a, posit b), and quire_mul(posit a, posit b). These two functions produce unrounded adds and multiplies and can be send to a quire, typically like so:

```
quire<nbits, es, capacity> q;
...
q += quire_mul(a, b);
...
```

These instructions are used to implement the fused dot product as shown below:
```
// Standalone fused dot product
template<size_t nbits, size_t es, size_t capacity = 10>
sw::unum::posit<nbits, es> fused_dot(size_t n, const std::vector< sw::unum::posit<nbits, es> >& x, size_t incx, const std::vector< sw::unum::posit<nbits, es> >& y, size_t incy) {
	sw::unum::quire<nbits, es, capacity> q = 0;
	size_t ix, iy;
	for (ix = 0, iy = 0; ix < n && iy < n; ix = ix + incx, iy = iy + incy) {
		q += sw::unum::quire_mul(x[ix], y[iy]);
		if (sw::unum::_trace_quire_add) std::cout << q << '\n';
	}
	sw::unum::posit<nbits, es> sum;
	convert(q.to_value(), sum);     // one and only rounding step of the fused-dot product
	return sum;
}
```
