### ISSUE TITLE
C api conversions between posits uses double

### ISSUE THREAD

**Issue by cjdelisle** [stillwater-sc/universal#90]
When converting from one posit type to another, the conversion implementation converts the posit to a double and then converts the double to the other type posit, which may lose bits.

**Comment by Ravenwater** [comment]
Yesterday, I implemented a generic cast that uses native bits, so we have the machinery to do it right.

Can you give me a line number of the code that this issue refers to?

**Comment by cjdelisle** [comment]
https://github.com/stillwater-sc/universal/blob/5466212dda316c63ee020aa383092fb0fb3cfdff/c_api/posit/posit_c_api.cpp#L255

**Comment by Ravenwater** [comment]
Closing issue as we are refactoring the library
